In [1]:
#Upload libraries
library(readr)
library(dplyr)
library(stringr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [6]:
setwd("/mnt/l/gtdbtk_out_colon02/")

In [3]:
#get unique species

all_gtdbtk_bac120_summary_colon02 <- read_delim("all_colon02_summ_gtdb_arch_bac.tsv", 
                                    delim = "\t", escape_double = FALSE, 
                                    trim_ws = TRUE)
head(all_gtdbtk_bac120_summary_colon02)

Rows: 111 Columns: 20
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (20): user_genome, classification, closest_genome_reference, closest_gen...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR1018185_M2-Pk008A.SZAXPI003409-8_bin.84
2 ERR1018186_M122A.SZAXPI003410-3_bin.46
3 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.45
4 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.21
5 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.42
6 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.48
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Paraprevotella;s__Paraprevotella clara
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Blautia_A;s__Blautia_A obeum
  closest_genome_reference closest_genome_reference_radius
1 GCA_025758045.1          95.0
2 GCF_900167555.1          95.0
3 GCF_900167555.1          95.0
4 GCF_000233955.1          95.0
5 GCF_900167555.1          95.0
6 GCF_025147765.1          95.0
  closest_genome_taxonomy
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Paraprevotella;s__Paraprevotella clara
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Blautia_A;s__Blautia_A obeum
  closest_genome_ani closest_genome_af closest_placement_reference
1 98.44              0.845             N/A
2 97.75              0.842             N/A
3 97.97              0.905             N/A
4 98.0               0.876             N/A
5 98.05              0.907             N/A
6 98.49              0.837             N/A
  closest_placement_radius closest_placement_taxonomy closest_placement_ani
1 N/A                      N/A                        N/A
2 N/A                      N/A                        N/A
3 N/A                      N/A                        N/A
4 N/A                      N/A                        N/A
5 N/A                      N/A                        N/A
6 N/A                      N/A                        N/A
  closest_placement_af pplacer_taxonomy classification_method
1 N/A                  N/A              ani_screen
2 N/A                  N/A              ani_screen
3 N/A                  N/A              ani_screen
4 N/A                  N/A              ani_screen
5 N/A                  N/A              ani_screen
6 N/A                  N/A              ani_screen
  note
1 classification based on ANI only
2 classification based on ANI only
3 classification based on ANI only
4 classification based on ANI only
5 classification based on ANI only
6 classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCA_963588145.1, s__Gemmiger sp963588145, 95.0, 89.78, 0.501; GCA_963655125.1, s__Gemmiger sp963655125, 95.0, 90.64, 0.565; GCA_004554775.1, s__Gemmiger variabilis_B, 95.0, 88.34, 0.446
2 GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 85.18, 0.253; GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 87.33, 0.365; GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 87.24, 0.391; GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 87.1, 0.307
3 GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 87.49, 0.407; GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 87.7, 0.386; GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 87.26, 0.309; GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 85.16, 0.255
4 GCF_000205165.1, s__Paraprevotella xylaniphila, 95.0, 92.55, 0.683
5 GCA_934502625.1, s__Gemmiger sp934502625, 95.0, 87.48, 0.316; GCF_024462815.1, s__Gemmiger sp900554145, 95.0, 85.44, 0.289; GCF_018784445.1, s__Gemmiger sp900540775, 95.0, 87.51, 0.416; GCA_025757985.1, s__Gemmiger sp900540595, 95.0, 87.3, 0.419
6 GCA_963622815.1, s__Blautia_A sp963622815, 95.0, 86.74, 0.269; GCF_900120195.1, s__Blautia_A sp900120195, 95.0, 84.16, 0.172; GCA_963597235.1, s__Blautia_A sp963597235, 95.0, 86.09, 0.251; GCF_934424005.1, s__Blautia_A sp934424005, 95.25, 95.22, 0.658; GCF_934372025.1, s__Blautia_A sp934372025, 95.0, 85.08, 0.215; GCF_040096655.1, s__Blautia_A intestinihominis, 95.0, 84.86, 0.151; GCA_900066355.1, s__Blautia_A sp900066355, 95.0, 84.12, 0.176; GCA_934378195.1, s__Blautia_A sp934378195, 95.0, 86.02, 0.287; GCF_018918125.1, s__Blautia_A sp018918125, 95.0, 84.9, 0.205; GCF_014297355.1, s__Blautia_A intestinalis, 95.0, 84.62, 0.177
  msa_percent translation_table red_value warnings
1 N/A         N/A               N/A       N/A
2 N/A         N/A               N/A       N/A
3 N/A         N/A               N/A       N/A
4 N/A         N/A               N/A       N/A
5 N/A         N/A               N/A       N/A
6 N/A         N/A               N/A       N/A

In [10]:
setwd("/mnt/l/colon2_hmmer_backup/")

In [11]:
# Upload result of checkm filtering

checkm_summary_colon02 <- read_delim("quality_report_bin_filtered_ID.tsv",
                                     delim = "\t", escape_double = FALSE, 
                                     trim_ws = TRUE, col_names = "user_genome")
head(checkm_summary_colon02)

Rows: 71 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): user_genome

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  user_genome
1 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.42
2 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.45
3 ERR1018186_M122A.SZAXPI003410-3_bin.46
4 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.4
5 ERR1018185_M2-Pk008A.SZAXPI003409-8_bin.84
6 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.48

In [12]:
# Filter ID based on checkm result
gtdbtk_bac120_summary_colon02 <- semi_join(all_gtdbtk_bac120_summary_colon02, checkm_summary_colon02, by= "user_genome")


#get species name
gtdbtk_classify_colon02 <- gtdbtk_bac120_summary_colon02[,"classification"]

gtdbtk_species_colon02 <- gtdbtk_classify_colon02 %>%
  mutate(species = str_extract(classification, "(?<=s__).*"))

gtdbtk_species_colon02$species <- trimws(gtdbtk_species_colon02$species)
gtdbtk_species_colon02$species[gtdbtk_species_colon02$species == ""] <- NA

unique(gtdbtk_species_colon02$species)

 [1] "Gemmiger sp900539695"            "Gemmiger formicilis"
 [3] "Paraprevotella clara"            "Blautia_A obeum"
 [5] "Escherichia coli"                "Fusobacterium_A mortiferum"
 [7] "Clostridium sp900540255"         "Fusobacterium_B sp900542625"
 [9] "Faecalibacillus intestinalis"    "Thomasclavelia ramosa"
[11] "Veillonella_A sp900545795"       "Agathobacter faecis"
[13] "Anaerostipes sp900066705"        "Romboutsia timonensis"
[15] "Agathobacter rectalis"           "Eubacterium_G ventriosum"
[17] "Turicibacter bilis"              NA
[19] "Phocaeicola massiliensis"        "Fusicatenibacter saccharivorans"
[21] "Ruminococcoides intestinale"     "Lachnospira eligens_A"
[23] "Bacteroides nordii"              "Parabacteroides gordonii"
[25] "Methanocatella smithii"

In [13]:
#count species match
table(gtdbtk_species_colon02$species)

count_gtdb_colon02 <- gtdbtk_species_colon02 %>%
  count(species, name = "occurrences")

View(count_gtdb_colon02)


unique_gtdbtk_species_colon02 <- gtdbtk_species_colon02 %>% distinct(species, .keep_all = TRUE)

unique_gtdbtk_species_colon02_ID <- unique_gtdbtk_species_colon02[,"species"]

            Agathobacter faecis           Agathobacter rectalis
                              3                               1
       Anaerostipes sp900066705              Bacteroides nordii
                              1                               1
                Blautia_A obeum         Clostridium sp900540255
                              1                               2
               Escherichia coli        Eubacterium_G ventriosum
                              6                               1
   Faecalibacillus intestinalis Fusicatenibacter saccharivorans
                              2                               1
     Fusobacterium_A mortiferum     Fusobacterium_B sp900542625
                              4                               1
            Gemmiger formicilis            Gemmiger sp900539695
                             28                               5
          Lachnospira eligens_A          Methanocatella smithii
                              1                               1
       Parabacteroides gordonii            Paraprevotella clara
                              1                               4
       Phocaeicola massiliensis           Romboutsia timonensis
                              1                               1
    Ruminococcoides intestinale           Thomasclavelia ramosa
                              1                               1
             Turicibacter bilis       Veillonella_A sp900545795
                              1                               1

   species                         occurrences
1  Agathobacter faecis              3
2  Agathobacter rectalis            1
3  Anaerostipes sp900066705         1
4  Bacteroides nordii               1
5  Blautia_A obeum                  1
6  Clostridium sp900540255          2
7  Escherichia coli                 6
8  Eubacterium_G ventriosum         1
9  Faecalibacillus intestinalis     2
10 Fusicatenibacter saccharivorans  1
11 Fusobacterium_A mortiferum       4
12 Fusobacterium_B sp900542625      1
13 Gemmiger formicilis             28
14 Gemmiger sp900539695             5
15 Lachnospira eligens_A            1
16 Methanocatella smithii           1
17 Parabacteroides gordonii         1
18 Paraprevotella clara             4
19 Phocaeicola massiliensis         1
20 Romboutsia timonensis            1
21 Ruminococcoides intestinale      1
22 Thomasclavelia ramosa            1
23 Turicibacter bilis               1
24 Veillonella_A sp900545795        1
25 NA                               1

In [ ]:
write_tsv(unique_gtdbtk_species_colon02_ID, "GTDB_results/unique_gtdbtk_species_colon02_ID.tsv")

In [14]:
################################################################################################################
#Division of disease versus Healthy


# Remove everything after the first "-"
gtdbtk_bac120_summary_colon02$ID <- sub("_.*", "", gtdbtk_bac120_summary_colon02$user_genome)

#get ID
gtdbtk_colon02_ID_name <- gtdbtk_bac120_summary_colon02[,"ID"]
head(gtdbtk_colon02_ID_name)

  ID
1 ERR1018185
2 ERR1018186
3 ERR1018187
4 ERR1018188
5 ERR1018188
6 ERR1018188

In [ ]:
#save file
write_tsv(gtdbtk_colon02_ID_name, "GTDB_results/gtdbtk_colon02_ID_name.tsv")

In [15]:
setwd("/mnt/l/Sia_git/metagen_files/")

In [17]:
#Upload data with health and disease ID. Put PATH to Metadata folder

#case
Study_2_china_cancer_case_Run_ID <- read_csv("Metadata/Study_2_china_cancer_case_Run_ID.tsv")

head(Study_2_china_cancer_case_Run_ID)

Rows: 75 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR1018185
2 ERR1018186
3 ERR1018187
4 ERR1018188
5 ERR1018189
6 ERR1018190

In [18]:
#control

Study_2_china_cancer_control_Run_ID <- read_csv("Metadata/Study_2_china_cancer_control_Run_ID.tsv")
head(Study_2_china_cancer_control_Run_ID)


#match and see how many match
colnames(gtdbtk_colon02_ID_name) <- "Run"

Rows: 53 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Run

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Run
1 ERR1018193
2 ERR1018195
3 ERR1018205
4 ERR1018209
5 ERR1018217
6 ERR1018232

In [19]:
#for case
match_colon02_case <- semi_join(gtdbtk_colon02_ID_name,Study_2_china_cancer_case_Run_ID, by= "Run")
nrow(match_colon02_case)

#get unique IDs
match_colon02_case_unique <- match_colon02_case %>% distinct(Run)
nrow(match_colon02_case_unique)

[1] 38

[1] 30

In [20]:
#for control
match_colon02_control <- semi_join(gtdbtk_colon02_ID_name,Study_2_china_cancer_control_Run_ID, by= "Run")
nrow(match_colon02_control)

#get unique IDs
match_colon02_control_unique <- match_colon02_control %>% distinct(Run)
nrow(match_colon02_control_unique)

[1] 33

[1] 29

In [21]:
#Final table 

cat_gtdk_ID <- merge(gtdbtk_bac120_summary_colon02,gtdbtk_species_colon02, by="classification")

cat_gtdk_ID_col <- cat_gtdk_ID[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species")]
nrow(cat_gtdk_ID)

cat_gtdk_ID_unique <- cat_gtdk_ID%>% distinct(user_genome,.keep_all=TRUE)
nrow(cat_gtdk_ID_unique)
head(cat_gtdk_ID_unique)

[1] 911

[1] 71

  classification
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Faecalibacillus;s__Faecalibacillus intestinalis
3 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Faecalibacillus;s__Faecalibacillus intestinalis
4 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Thomasclavelia;s__Thomasclavelia ramosa
5 d__Bacteria;p__Bacillota;c__Bacilli;o__MOL361;f__Turicibacteraceae;g__Turicibacter;s__Turicibacter bilis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Clostridiales;f__Clostridiaceae;g__Clostridium;s__Clostridium sp900540255
  user_genome                                 closest_genome_reference
1 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.4   GCF_000016525.1
2 ERR1018209_509A.SZAXPI003433-7_bin.26       GCF_003024685.1
3 ERR1018280_M2-PK045A.SZAXPI017452-17_bin.31 GCF_003024685.1
4 ERR1018210_M113A.SZAXPI003434-7_bin.29      GCF_014131695.1
5 ERR1018229_M2-PK027A.SZAXPI015224-13_bin.16 GCF_024499055.1
6 ERR1018256_M2-PK619A.SZAXPI015252-43_bin.40 GCF_039753335.1
  closest_genome_reference_radius
1 95.0
2 95.0
3 95.0
4 95.0
5 95.0
6 95.0
  closest_genome_taxonomy
1 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
2 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Faecalibacillus;s__Faecalibacillus intestinalis
3 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Faecalibacillus;s__Faecalibacillus intestinalis
4 d__Bacteria;p__Bacillota;c__Bacilli;o__Erysipelotrichales;f__Coprobacillaceae;g__Thomasclavelia;s__Thomasclavelia ramosa
5 d__Bacteria;p__Bacillota;c__Bacilli;o__MOL361;f__Turicibacteraceae;g__Turicibacter;s__Turicibacter bilis
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Clostridiales;f__Clostridiaceae;g__Clostridium;s__Clostridium sp900540255
  closest_genome_ani closest_genome_af closest_placement_reference
1 99.17              0.918             N/A
2 98.38              0.682             N/A
3 98.76              0.788             N/A
4 99.68              0.816             N/A
5 98.74              0.858             N/A
6 99.14              0.855             N/A
  closest_placement_radius closest_placement_taxonomy ⋯ pplacer_taxonomy
1 N/A                      N/A                        ⋯ N/A
2 N/A                      N/A                        ⋯ N/A
3 N/A                      N/A                        ⋯ N/A
4 N/A                      N/A                        ⋯ N/A
5 N/A                      N/A                        ⋯ N/A
6 N/A                      N/A                        ⋯ N/A
  classification_method note
1 ani_screen            classification based on ANI only
2 ani_screen            classification based on ANI only
3 ani_screen            classification based on ANI only
4 ani_screen            classification based on ANI only
5 ani_screen            classification based on ANI only
6 ani_screen            classification based on ANI only
  other_related_references(genome_id,species_name,radius,ANI,AF)
1 GCA_963606955.1, s__Methanocatella sp963606955, 95.0, 88.37, 0.521; GCF_023617305.1, s__Methanocatella smithii_A, 95.0, 93.91, 0.834; GCF_934746965.1, s__Methanocatella sp934746965, 95.0, 87.41, 0.467
2 GCA_958421935.1, s__Faecalibacillus sp900544435, 95.0, 93.0, 0.447; GCF_003024675.1, s__Faecalibacillus faecis, 95.0, 91.11, 0.307; GCA_963618275.1, s__Faecalibacillus sp963618275, 95.0, 91.23, 0.413; GCA_030540195.1, s__Faecalibacillus sp030540195, 95.0, 90.35, 0.292
3 GCA_030540195.1, s__Faecalibacillus sp030540195, 95.0, 89.79, 0.4; GCA_958421935.1, s__Faecalibacillus sp900544435, 95.0, 92.92, 0.597; GCA_963618275.1, s__Faecalibacillus sp963618275, 95.0, 91.45, 0.495; GCF_003024675.1, s__Faecalibacillus faecis, 95.0, 90.56, 0.446
4 N/A
5 N/A
6 GCF_015555905.1, s__Clostridium sp015555905, 95.0, 84.02, 0.155; GCF_000577815.1, s__Clostridium saudiense, 95.0, 85.67, 0.245; GCF_015670405.1, s__Clostridium sp015670405, 95.0, 85.15, 0.229; GCF_934754925.1, s__Clostridium sp934754925, 95.0, 84.51, 0.158; GCF_019734195.1, s__Clostridium sp900766315, 95.0, 84.5, 0.155; GCF_004353185.1, s__Clostridium cuniculi, 95.0, 83.89, 0.16
  msa_percent translation_table red_value warnings ID
1 N/A         N/A               N/A       N/A      ERR1018187
2 N/A         N/A               N/A       N/A      ERR1018209
3 N/A         N/A               N/A       N/A      ERR1018280
4 N/A         N/A               N/A       N/A      ERR1018210
5 N/A         N/A               N/A       N/A      ERR1018229
6 N/A         N/A               N/A       N/A      ERR1018256
  species
1 Methanocatella smithii
2 Faecalibacillus intestinalis
3 Faecalibacillus intestinalis
4 Thomasclavelia ramosa
5 Turicibacter bilis
6 Clostridium sp900540255

In [22]:
cat_gtdk_ID_col <- cat_gtdk_ID_unique[,c("classification","closest_genome_reference","closest_genome_ani", "ID", "species", "user_genome")]


cat_colon02_preview <- merge(cat_gtdk_ID_col,count_gtdb_colon02, by= "species")
head(cat_colon02_preview)

  species
1 Agathobacter faecis
2 Agathobacter faecis
3 Agathobacter faecis
4 Agathobacter rectalis
5 Anaerostipes sp900066705
6 Bacteroides nordii
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter faecis
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter faecis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter faecis
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter;s__Agathobacter rectalis
5 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Anaerostipes;s__Anaerostipes sp900066705
6 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides;s__Bacteroides nordii
  closest_genome_reference closest_genome_ani ID
1 GCF_001406815.1          98.77              ERR1018235
2 GCF_001406815.1          97.9               ERR1018212
3 GCF_001406815.1          98.17              ERR1018211
4 GCF_000020605.1          97.13              ERR1018227
5 GCA_902362875.1          98.43              ERR1018215
6 GCA_000613465.1          98.78              ERR1018292
  user_genome                                  occurrences
1 ERR1018235_519A.SZAXPI015230-16_bin.41       3
2 ERR1018212_M2-Pk009A.SZAXPI003436-7_bin.27   3
3 ERR1018211_M2-Pk016A.SZAXPI003435-11_bin.51  3
4 ERR1018227_M2-PK002A.SZAXPI015222-123_bin.53 1
5 ERR1018215_M2-PK037B.SZAXPI015210-17_bin.49  1
6 ERR1018292_M2-PK084A.SZAXPI017464-37_bin.22  1

In [23]:
# handling with control and disease column

match_colon02_control$State <- "Control"
match_colon02_case$State <- "Disease"

# Change column name

colnames(match_colon02_control)[colnames(match_colon02_control) == "Run"] <- "ID"
colnames(match_colon02_case)[colnames(match_colon02_case) == "Run"] <- "ID" 

all_state <- rbind(match_colon02_control,match_colon02_case)

cat_colon02_final <- merge(cat_colon02_preview,all_state, by= "ID")
head(cat_colon02_final)

  ID         species
1 ERR1018185 Gemmiger sp900539695
2 ERR1018186 Gemmiger formicilis
3 ERR1018187 Gemmiger formicilis
4 ERR1018187 Gemmiger formicilis
5 ERR1018187 Methanocatella smithii
6 ERR1018187 Methanocatella smithii
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
5 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
6 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
  closest_genome_reference closest_genome_ani
1 GCA_025758045.1          98.44
2 GCF_900167555.1          97.75
3 GCF_900167555.1          97.97
4 GCF_900167555.1          97.97
5 GCF_000016525.1          99.17
6 GCF_000016525.1          99.17
  user_genome                                occurrences State
1 ERR1018185_M2-Pk008A.SZAXPI003409-8_bin.84  5          Disease
2 ERR1018186_M122A.SZAXPI003410-3_bin.46     28          Disease
3 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.45 28          Disease
4 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.45 28          Disease
5 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.4   1          Disease
6 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.4   1          Disease

In [24]:
cat_colon02_final_end <- cat_colon02_final %>% distinct(user_genome, .keep_all = TRUE)
nrow(cat_colon02_final_end)

[1] 71

In [ ]:
#save output. Put PATH to Study02_colon_cancer folder
write_tsv(cat_colon02_final_end, "GTDB_results/final_table_gtdb_for_paper_colon02.tsv")
write_tsv(count_gtdb_colon02, "GTDB_results/species_occurrence.tsv")

In [25]:
# Classify species
classification <- cat_colon02_final_end %>%
  filter(!is.na(species), !is.na(State)) %>%
  group_by(species) %>%
  summarise(
    Group_classification = case_when(
      n_distinct(State) == 1 & first(State) == "Disease" ~ "Disease",
      n_distinct(State) == 1 & first(State) == "Control" ~ "Control",
      n_distinct(State) > 1 ~ "Control/Disease"
    ),
    .groups = "drop"
  )

# Join  and apply rule for Species == NA
cat_colon02_final_end_df <- cat_colon02_final_end %>%
  left_join(classification, by = "species") %>%
  mutate(
    Group_classification = ifelse(
      is.na(species),
      State,
      Group_classification
    )
  )

head(cat_colon02_final_end_df)

  ID         species
1 ERR1018185 Gemmiger sp900539695
2 ERR1018186 Gemmiger formicilis
3 ERR1018187 Gemmiger formicilis
4 ERR1018187 Methanocatella smithii
5 ERR1018188 Paraprevotella clara
6 ERR1018188 Blautia_A obeum
  classification
1 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger sp900539695
2 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
3 d__Bacteria;p__Bacillota;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger;s__Gemmiger formicilis
4 d__Archaea;p__Methanobacteriota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanocatella;s__Methanocatella smithii
5 d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Paraprevotella;s__Paraprevotella clara
6 d__Bacteria;p__Bacillota;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Blautia_A;s__Blautia_A obeum
  closest_genome_reference closest_genome_ani
1 GCA_025758045.1          98.44
2 GCF_900167555.1          97.75
3 GCF_900167555.1          97.97
4 GCF_000016525.1          99.17
5 GCF_000233955.1          98.0
6 GCF_025147765.1          98.49
  user_genome                                occurrences State
1 ERR1018185_M2-Pk008A.SZAXPI003409-8_bin.84  5          Disease
2 ERR1018186_M122A.SZAXPI003410-3_bin.46     28          Disease
3 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.45 28          Disease
4 ERR1018187_M2-Pk010A.SZAXPI003411-6_bin.4   1          Disease
5 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.21  4          Disease
6 ERR1018188_M2-Pk014A.SZAXPI003412-1_bin.48  1          Disease
  Group_classification
1 Control/Disease
2 Control/Disease
3 Control/Disease
4 Disease
5 Control/Disease
6 Disease

In [ ]:
write_tsv(cat_colon02_final_end_df,"GTDB_results/gtdb_final_table_with_condition_colon02_corrigido.tsv")

In [26]:
cat_colon02_final_end_df_col <- cat_colon02_final_end_df[ ,c("species", "occurrences", "Group_classification")]

cat_colon02_final_end_df_col_unique <- cat_colon02_final_end_df_col %>% distinct(species, .keep_all = TRUE)

In [ ]:
write_tsv(cat_colon02_final_end_df_col_unique, "GTDB_results/count_ocurrence_w_condition_for_paper_colon02.tsv")